# Generated by Django 6.0.8 on 2026-08-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('Study Tips', 'Study Tips'), ('Education', 'Education'), ('Online Learning', 'Online Learning'), ('Tutoring', 'Tutoring'), ('Exams', 'Exams'), ('Career', 'Career')], default='Education', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('excerpt', models.TextField(help_text='Short description shown on the blog card.', max_length=300)),
                ('content', models.TextField(help_text='Full article content.')),
                ('author', models.CharField(default='Tutorverse', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
