# Generated by Django 6.0.8 on 2026-08-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='categories.subject'),
        ),
    ]
