# Generated by Django 6.0.8 on 2026-08-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacherprofile_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
