# Generated by Django 6.0.8 on 2026-08-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacherprofile_latitude_teacherprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='teacher_videos/'),
        ),
    ]
