# Generated by Django 6.0.8 on 2026-08-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacherprofile_intro_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='identity_document',
            field=models.FileField(blank=True, help_text='Upload a valid government-issued ID.', null=True, upload_to='teacher_identity_documents/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='identity_document_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('drivers_license', "Driver's License"), ('passport', 'International Passport'), ('voters_card', "Voter's Card"), ('other', 'Other')], max_length=50),
        ),
    ]
