# Generated by Django 6.0.8 on 2026-08-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='education_level',
            field=models.CharField(choices=[('secondary', 'Secondary Education'), ('tertiary', 'Tertiary Education')], default='secondary', max_length=20),
        ),
    ]
